### ISSUE TITLE
Consider yanking 1.0.0-alpha1 and publishing 0.7

### ISSUE THREAD

**Issue by nox** [TyOverby/bincode#106]
https://github.com/TyOverby/bincode/commit/ff3dab845a6d2904b009455583da4e67ce3a8a2c#commitcomment-20696129

**Comment by TyOverby** [comment]
I'm wanted to publish bincode 1.0.0 as soon as procedural macros land in stable. 

I'm totally fine with pushing a new major version of bincode every month or so.

**Comment by nox** [comment]
Fair enough!
