### ISSUE TITLE
Add benchmark suite

### ISSUE THREAD

**Issue by TyOverby** [TyOverby/bincode#112]
(not blocking for 1.0)

It would be nice to have a benchmark suite so that it is easy to measure versions of serde and our ser/de implementations.

**Comment by dgriffen** [comment]
Currently the built-in benchmarking in Rust is nightly only. Is the plan to use that and only run benchmarks on nightly or is there another tool we can use.

**Comment by dtolnay** [comment]
I have a benchmark here that tests a bincode-like format against serde_json on some common benchmark datasets from the C/C++ world.

https://github.com/serde-rs/json-benchmark/blob/master/src/binary.rs

**Comment by TyOverby** [comment]
@dgriffen I was just going to go for nightly-only benchmarks, but if there's another benchmark runner, I'd be happy using that .

@dtolnay Great!  Looks like a perfect starting point!

**Comment by TyOverby** [comment]
bincode-bench was written a while ago
