### ISSUE TITLE
Implement From<IoError> for SerializeError

### ISSUE THREAD

**Issue by nox** [TyOverby/bincode#113]

**Comment by TyOverby** [comment]
SerializeError is gone, replaced with an Error struct for both serialization and deserialization.

I just checked, and From<IoError> is implemented for this new struct.

**Comment by nox** [comment]
Could you publish alpha1 or something with that change, so that I progress on Servo's serde bump?

**Comment by TyOverby** [comment]
`1.0.0-alpha2` has been published
