### ISSUE TITLE
Wasteful Vec allocation in read_string and read_vec

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#118]
Every String and Vec\<u8> deserialization (as of #115) allocates a fresh vector. From what we've seen in the JSON deserializer, reusing a [long-lived buffer](https://github.com/serde-rs/json/blob/v0.9.8/json/src/de.rs#L20) would be a huge improvement.

**Comment by khuey** [comment]
This optimization would only affect the `deserialize_bytes` case.  Both `deserialize_byte_buf` and `deserialize_string` want to consume the buffer to produce zero-copy output.

**Comment by TyOverby** [comment]
@khuey: also `deserialize_str`

**Comment by khuey** [comment]
Yes, forgot that one.
