### ISSUE TITLE
Specialize for deserializing from &[u8]

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#119]
Like [in the JSON deserializer](https://github.com/serde-rs/json/blob/v0.9.8/json/src/de.rs#L1072-L1076), Bincode should have a specialized codepath for deserializing from &[u8]. This is an enormous improvement because it would no longer require copying strings into a temp buffer.

**Comment by TyOverby** [comment]
When you say "specialized", do you mean, like, the Rust language feature "specialization"?  

If so, I'm not seeing how that is used in the json deserializer.

**Comment by dtolnay** [comment]
Eventually once specialization is stable, yes. For now it is done with [this trait](https://github.com/serde-rs/json/blob/v0.9.8/json/src/read.rs#L7-L9) by having the caller select the right entry point based on the type of data that they have - [from_slice](https://docs.serde.rs/serde_json/fn.from_slice.html) vs [from_str](https://docs.serde.rs/serde_json/fn.from_str.html) vs [from_reader](https://docs.serde.rs/serde_json/fn.from_reader.html) vs [from_iter](https://docs.serde.rs/serde_json/fn.from_iter.html).

**Comment by TyOverby** [comment]
I'm not a huge fan of adding a non-standard Read trait for this :/ 

I also don't think that Bincode will benefit from this as much as Json would.  Because everything that comes out of bincode must be owned, practically every structure that gets deserialized will be copied.

**Comment by TyOverby** [comment]
I've used Bincode a lot for network communication and save-games and I've never written any code that would hit this optimization.  In fact, I think you'd need to custom-implement the Serde Deserialize trait in order to get any benefit.

**Comment by dtolnay** [comment]
Ah yeah, deserialize_str is the overwhelmingly common case for JSON but for Bincode it is deserialize_string. Good call.

**Comment by TyOverby** [comment]
re-opening and adding to milestone: unknown.  Some people doing custom deserialize implementations could benefit from this.  But I think we should wait until stabilization stabilizes.

**Comment by dtolnay** [comment]
What are the objections against using a trait for this in lieu of specialization?

**Comment by TyOverby** [comment]
As I understand it, the trait would have to be exposed to the user right?  I'd rather have Bincode use traits and types just from `std` and `serde`.

**Comment by dtolnay** [comment]
Yes but the vast majority of users never see it. Most people just use [this function](https://github.com/serde-rs/json/blob/bbbef90c17dfbea20057833ca5537c689261bec5/json/src/de.rs#L1072-L1076) where they pass in a &[u8] and they get back a T.

```rust
pub fn from_slice<T>(v: &[u8]) -> Result<T>
    where T: de::Deserialize,
{
    from_trait(read::SliceRead::new(v))
}
```

Or [this function](https://github.com/serde-rs/json/blob/bbbef90c17dfbea20057833ca5537c689261bec5/json/src/de.rs#L1056-L1061) where they pass in an `io::Read` and get back a T.

```rust
pub fn from_reader<R, T>(rdr: R) -> Result<T>
    where R: io::Read,
          T: de::Deserialize,
{
    from_iter(rdr.bytes())
}
```

Really the only time a user would see this is in the rare case that someone stores a long-lived deserializer (typically a stream deserializer) in a struct, but that is almost nobody:

```rust
struct MyStruct<R: serde_json::de::Read> {
    the_goods: serde_json::StreamDeserializer<R, serde_json::Value>,
}
```

**Comment by dgriffen** [comment]
Isn't this now resolved since we have the `BincodeRead` trait and the `SliceReader` impl?

**Comment by TyOverby** [comment]
@dgriffen: yeah, this should be closed
