### ISSUE TITLE
Optimize bincode::deserialize

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#122]
```rust
pub fn deserialize<T>(bytes: &[u8]) -> Result<T>
    where T: serde::Deserialize
{
    let mut reader = bytes;
    deserialize_from(&mut reader, SizeLimit::Infinite)
}
```

This function is inefficient because in addition to a bunch of sizelimit-related branching (cc #121) the deserializer is forced to perform two writes for every time it reads from the input - once within `self.reader` and another to update `self.read` - even though `self.read` is never going to be used.

A specialized implementation for &[u8] would enable optimizing this case to perform just a single write - cc #119.

**Comment by TyOverby** [comment]
Fixed a long time ago with the SizeLimit trait
