### ISSUE TITLE
Release bincode 0.7

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#148]
Serde 1.0 is happening in the next 6 weeks or so. Until then how about publishing bincode 0.7 with serde 0.9 support, then doing 1.0 along with us?

**Comment by TyOverby** [comment]
Sounds good!

**Comment by TyOverby** [comment]
I assume that you meant bincode 1.0.0-alpha7?

Also, are you publishing alpha versions of serde on crates.io?

**Comment by dtolnay** [comment]
Nope, I meant bincode 0.7.0 with support for serde 0.9. I am not publishing alpha versions.

**Comment by TyOverby** [comment]
Ah ok.  I just published 0.7.0.  

> I am not publishing alpha versions.

Should I target your  github branch for now then?

**Comment by dtolnay** [comment]
Publishing alpha versions is a bad idea in general because of https://github.com/rust-lang/cargo/issues/2222 - see https://github.com/TyOverby/bincode/pull/128#issuecomment-283525730. I will publish release candidate versions (rc1, rc2 etc) when I am ready. I would recommend that you maintain a branch that targets serde's "1.0" branch, not publish anything to crates.io until there is a serde release candidate, and yank your existing alpha versions to push people to use bincode 0.7.
