### ISSUE TITLE
Publish new alpha with serde 1.0 support

### ISSUE THREAD

**Issue by bjorn3** [TyOverby/bincode#153]

**Comment by Xaeroxe** [comment]
Hey so I'd like to help with this.  Where should I start?

**Comment by bjorn3** [comment]
This is something the maintainer should do. Master already supports serde 1.0

**Comment by Xaeroxe** [comment]
Thanks, sorry I thought there was additional coding work to be done

**Comment by TyOverby** [comment]
Because alphas have some serious usability issues, I've pushed as `0.8.0`.

**Comment by bjorn3** [comment]
Thanks
