### ISSUE TITLE
Functions `deserialize` and `deserialize_from` are confusing

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#155]
It sounds like we picked two different names for the same thing and randomly allocated one to each signature. Both functions are deserializing from something.

**Comment by TyOverby** [comment]
`deserialize_slice` and `deserialize_from_reader)`?

Same argument applies to the encoding APIs as well

**Comment by TyOverby** [comment]
`deserialize_slice` and `deserialize_from_reader`?

Same argument applies to the encoding APIs as well

**Comment by dtolnay** [comment]
The Rust convention is `from_xyz`.

- [`str::from_utf8`](https://doc.rust-lang.org/std/str/fn.from_utf8.html) - the input is UTF-8 bytes that should be interpreted as a str.
- [`slice::from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html) - the input is raw parts that should be interpreted as a slice.
- [`serde_json::from_str`](https://docs.serde.rs/serde_json/fn.from_str.html) - the input is a str that should be interpreted as JSON.
