### ISSUE TITLE
Rename or hide bincode::internal

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#156]
It is confusing to have this module with a ton of public functionality in it. Am I allowed to use it? Is it reserved for internal bincode use? What makes it internal? Why is it public and visible in the docs?

**Comment by TyOverby** [comment]
It should probably be renamed back to "endian_choice"

**Comment by dtolnay** [comment]
I don't understand the logic for all of what is currently in `internal` but a simpler `bincode::endian::Deserializer` makes perfect sense to me. Things that have nothing to do with endian choice (like ErrorKind) should probably not be exported under `endian_choice`.
