### ISSUE TITLE
Reader and writer should be taken by value

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#159]
```rust
pub fn deserialize_from<R: ?Sized, T, S>(reader: &mut R, size_limit: S)

pub fn serialize_into<W: ?Sized, T: ?Sized, S>(writer: &mut W, value: &T, size_limit: S)
```

This is obnoxious when reading or writing some IO stream that is used only for bincode.

```rust
bincode::deserialize_from(File::open(f)?, infinite)
```

The standard library implements Read for &mut R and Write for &mut W so if these methods take the argument by value, callers can keep passing &mut like before if they want.

**Comment by TyOverby** [comment]
Agree

**Comment by fadeevab** [comment]
For anyone who wonders what to do now to not move the reader:
```rust
let f = File::open(f)?;
bincode::deserialize_from(f.by_ref(), infinite)?; // reference is moved, file is not
bincode::deserialize_from(f.by_ref(), infinite)?; // reference is moved, file is not
bincode::deserialize_from(f, infinite)?; // file is moved, you cannot use one further
```

**Comment by I3ck** [comment]
I wanted to port some of my code to bincode.  
```rust
fn foo<R>(read: &mut R) 
  where
    R: Read {
      let count = //read from file format
      for _ in 0..count {
          //this won't work, since read is moved in previous iteration
          let x: SomeType = bincode::deserialize_from(read)?;
          //use x
      }
}
```
Note that I am reading a foreign file format and can't 'just' derive `Deserialize` for the entire data/file.  
I'd have to add additional type constrains to `foo` to resolve this.  
Would it make sense to offer both overloads in the future?

**Comment by ofadieiev** [comment]
@I3ck doesn't `read.by_ref()`  work for you?

**Comment by fadeevab** [comment]
@I3ck doesn't read.by_ref() work for you?

**Comment by I3ck** [comment]
I assumed it was part of `File` not `Read`.
Sorry, my bad (it should work)
