### ISSUE TITLE
Error message for sequence without a known length

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#165]
> bincode can't encode infinite sequences

A couple things:

- Neither can Serde!
- This message is used for maps too, so it should be more general or split into two messages.
- This message doesn't help the user fix the problem. ("Make your sequence less infinite"?)

**Comment by dtolnay** [comment]
Something like this might work better:

> Bincode requires sequence length to be available before serializing any elements

**Comment by TyOverby** [comment]
Fixed in eddf897
