### ISSUE TITLE
no_std support? 

### ISSUE THREAD

**Issue by vitiral** [TyOverby/bincode#189]
I didn't see no_std support in the documentation / cargo.toml / issues so I thought I would open one. This library seems perfect for no_std serialization in microcontrollers. What are the biggest barriers to supporting no_std? Would you welcome a PR that did so?

Thanks!

**Comment by dtolnay** [comment]
Yes! I don't know what the biggest barriers are but we would love a PR to support no_std.

**Comment by vitiral** [comment]
A rough design could be:
- have std feature for current functionality, and `default-features = false` mean no_std
- when not feature=std:
  - don't use anything from the `io` module (std only), instead use buffer pointers
  - errors/expect/etc shouldn't use strings (or use very short ones) to stay as memory efficient as possible. 
- use [`default-features = false`](https://serde.rs/feature-flags.html) on serde along with the conditional cargo feature (rust-lang/cargo#633) 

Theoretically I hope that's it! Not a small amount of work, but hopefully doable

**Comment by vitiral** [comment]
I'm going to try and give this a shot this week

**Comment by vitiral** [comment]
It looks like we depend on rust-num/num#296, which is an open PR that will hopefully be done soonish!

**Comment by vks** [comment]
rust-num/num#296 has been merged, num-traits 0.1.38 can be build without std.

**Comment by vitiral** [comment]
I took an initial stab at this and it is way more difficult than I first anticipated. 

Also, ssmarshall does pretty much everything I needed

https://crates.io/crates/ssmarshal

Not sure where this issue should go, but I won't be working on it!

**Comment by vitiral** [comment]
Thus crate could be no_std, but it would basically be ssmarshall with u32 enumerated variants and optional bit ordering

**Comment by TyOverby** [comment]
Yeah... bincode is pretty dependent on `std::io::Write` and `std::io::Read` which isn't `no_std` compatible.

**Comment by astraw** [comment]
[core_io](https://crates.io/crates/core_io)'s documentation says that it provides the Read and Write traits for use with `core` and does not require `std`. I have not tried it myself.

**Comment by vlad9486** [comment]
Take a look on my crate [tirse](https://crates.io/crates/tirse). I just committed, the work still in progress.

**Comment by noonien** [comment]
Any update on this?

**Comment by vks** [comment]
I think no_std support is not intended for bincode. Such support would likely require significant limitations, see the ssmarshall crate, which is essentially a reimagination of bincode for no_std applications.

**Comment by noonien** [comment]
The no_std story has really changed since 2 years ago. It's a lot easier to provide no_std support nowadays.

**Comment by vitiral** [comment]
some context: there IS a protobuf implementation (in C) for micro-controllers:
https://github.com/nanopb/nanopb
