### ISSUE TITLE
Yank 1.0.0-alpha releases

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#190]
The crates.io page is still extremely misleading. It is almost impossible to tell that 0.8.0 is newer code than any of these alpha releases. See the confusion in https://github.com/chronotope/chrono/pull/160.

```
cargo yank --vers 1.0.0-alpha1 bincode
cargo yank --vers 1.0.0-alpha2 bincode
cargo yank --vers 1.0.0-alpha3 bincode
cargo yank --vers 1.0.0-alpha4 bincode
cargo yank --vers 1.0.0-alpha5 bincode
cargo yank --vers 1.0.0-alpha6 bincode
cargo yank --vers 1.0.0-alpha7 bincode
```

**Comment by dtolnay** [comment]
Assigning to @nox and @TyOverby who are the owners on crates.io.

**Comment by TyOverby** [comment]
Done

**Comment by TyOverby** [comment]
@dtolnay You've also been added as an owner
