### ISSUE TITLE
Reader and Writer are deprecated.

### ISSUE THREAD

**Issue by alexchandel** [TyOverby/bincode#20]
This needs to find replacement methods for reading ints/floats.

**Comment by TyOverby** [comment]
Yep, I'm going to use https://github.com/BurntSushi/byteorder when it starts using `newio`.

**Comment by TyOverby** [comment]
You can now use the `newio` branch if you want.

**Comment by alexchandel** [comment]
There is no `newio` in byteorder. It currently works with the new `io` though. And I'm not interested in using branches, only crates.io. It may be time to merge and `cargo upload` your `newio` branch.

**Comment by TyOverby** [comment]
There's a few people depending on the old-io version.  I'll ask around and see if they are ready to change.

**Comment by TyOverby** [comment]
@viperscape: Would you be ready to move to the new io crate?

**Comment by viperscape** [comment]
Yes, sounds great

**Comment by TyOverby** [comment]
Ok, it's pushed and published.
