### ISSUE TITLE
Why is Error a Box<ErrorKind>?

### ISSUE THREAD

**Issue by Cobrand** [TyOverby/bincode#202]
What makes the `Box<_>` necessary in the `type Error = Box<ErrorKind>` definition? As far as I've seen there is no mention of that either in the doc or in the code, and if I recall well it didn't use to have a Box<_> there.

**Comment by dgriffen** [comment]
I can't find the issue where this was changed at the moment. But if I remember correctly is was an optimization because by boxing up the errors less bytes had to be put on the stack for returns.

**Comment by TyOverby** [comment]
@Cobrand: we ran performance tests and found that allocating a Box and copying the box around the stack was cheaper than copying the error value around the stack.

**Comment by Cobrand** [comment]
It used to be pretty simple to match all possibilities with one `match`, now without the (unstable) box pattern you have to use 2 `match` to get to the same result, that's why I asked why it changed.

Thanks for answering!

**Comment by TyOverby** [comment]
You should be able to use a single `*` to dereference and then you can match just like before
