### ISSUE TITLE
bincode crate on crates.io contains large logo.png file unnecessarily

### ISSUE THREAD

**Issue by staktrace** [TyOverby/bincode#213]
While I appreciate the artistry involved in logo.png, it doesn't seem useful to include that file (or the readme.md/readme.dev.md files) into the packaged crate on crates.io. Currently the published bincode-0.9.0 crate is 72351 bytes and without these files the crate would be only 14601 bytes.

This probably doesn't seem like much, but the logo.png file is 258k uncompressed, which exceeds the 100k file size limit for automatic vendoring into the mozilla-central repository for use in Firefox. It's possible but annoying to work around this, and these files are unnecessary in the packaged crate anyway, so it would be nice to drop them.

**Comment by TyOverby** [comment]
Wow that's unfortunate. 

I've pushed `0.9.1` which has excluded the image.  I've kept the readme file because I think it's necessary to get readme rendering in crates.io.  I'll experiment with that and see if it's actually necessary.

**Comment by staktrace** [comment]
Thanks for the quick turnaround!

**Comment by staktrace** [comment]
As far as I can tell the exclude you added to Cargo.toml *should* work. The only difference I can see from other exclude statements I've used successfully in the past is that you have the "./" at the front of the filename whereas I never had that. Maybe that makes a difference?

**Comment by TyOverby** [comment]
I've pushed 0.9.2 which I've verified does not contain logo.png.

I've also excluded tests, examples, changelist, and LICENSE because they're not necessary in the package.

**Comment by TyOverby** [comment]
And yeah, apparently it was an issue with relative paths.  Really unexpected issue.

**Comment by staktrace** [comment]
Great, thanks!
