### ISSUE TITLE
Option to set the bytes used for encoding str?

### ISSUE THREAD

**Issue by tejom** [TyOverby/bincode#226]
Hey,

I thought it might interesting to use this library to decode a network protocol. The protocol Im working with uses one byte to determine the length of a string. Would be it be possible to have an option that sets the amount of bytes used when encoding or decoding?

Something I tried was this 

    fn deserialize_str<V>(self, visitor: V) -> Result<V::Value>
        where
            V: serde::de::Visitor<'de>,
    {
        #[cfg(feature="len_u8")]
        let len: u8 = serde::Deserialize::deserialize(&mut *self)?;

        #[cfg(feature="len_usize")]
        let len: usize = serde::Deserialize::deserialize(&mut *self)?;

        self.read_bytes(len as u64)?;
        self.reader.forward_read_str(len as usize, visitor)
    }

This struct

    struct Point<'a> {
      x: u8,
      y: u8,
      s: &'a str,
    }

would be encoded like this
`[100,78,4,116,101,115,116]`

instead of 

`[100, 78, 4, 0, 0, 0, 0, 0, 0, 0, 116, 101, 115, 116]`

**Comment by TyOverby** [comment]
Nope, not possible.  If you are decoding a network protocol, I'd recommend taking a look at Nom.
