### ISSUE TITLE
Borrowed Cow<'_, [u8]> fails if raw bytes not valid utf8

### ISSUE THREAD

**Issue by daboross** [TyOverby/bincode#231]
I thought I was going crazy for a while, so I might still be, but this seems to be a bug in bincode or serde?

This code:

```rust
extern crate bincode;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::borrow::Cow;

#[derive(Debug, Serialize, Deserialize)]
pub struct X<'a> {
    #[serde(borrow)]
    pub field: Cow<'a, [u8]>,
}


fn main() {
    let original = X { field: [255, 255, 255, 255][..].into() };

    let ser = bincode::serialize(&original).expect("expected serialization to succeed");
    let _: X = bincode::deserialize(&ser).expect("expected same encoded bytes to decode");

}
```

fails with:

```
thread 'main' panicked at 'expected same encoded bytes to decode: InvalidUtf8Encoding(Utf8Error { valid_up_to: 0, error_len: Some(1) })', libcore/result.rs:945:5
```

I'm not serializing or deserializing any strings, so I am assuming this is a bug. If it's not, could there be another way to fix this?

It does work correctly (accepting invalid UTF8 bytes) if I use either `Vec<u8>` or `&'a [u8]`.

Thanks!

**Comment by TyOverby** [comment]
This is super weird.  I can't find any code in bincode or serde that would do this.

CC @dtolnay

**Comment by daboross** [comment]
Could be https://github.com/serde-rs/serde/blob/master/serde/src/private/de.rs#L191?

I'll try changing that and see if it fixes anything.

**Comment by dtolnay** [comment]
Yes I had just found the same thing. That does fix it. Want to send a PR?

**Comment by daboross** [comment]
Sure, will do.
