### ISSUE TITLE
Support 128bit integers

### ISSUE THREAD

**Issue by KodrAus** [TyOverby/bincode#236]
`serde` ~~`1.0.62`~~ `1.0.60` was recently released with optional support for 128bit numbers. It would be good if we could wire them up to `bincode`. There's a convenient `serde_if_integer128!` macro that `serde` exposes we could use to automatically detect newer compilers, but that might not line up so well with `byteorder`'s explicit `i128` feature. Maybe we could do something like this:

In `Cargo.toml`:

```toml
[features]
i128 = ["byteorder/i128"]
```

In `ser.rs` or `de.rs`:

```rust
impl Serializer {
    serde_if_integer128! {
        #[cfg(feature = "i128")]
        fn serialize_i128(self, v: i128) -> Result<Self::Ok, Self::Error> {
            // use `byteorder` to serialize our value
        }

        #[cfg(not(feature = "i128"))]
        fn serialize_i128(self, v: i128) -> Result<Self::Ok, Self::Error> {
            let _ = v;
            Err(Error::custom("i128 is not supported. Enable the `i128` feature of `bincode`"))
        }

        ...
    }
}
```

so that vanilla `bincode` keeps working on older compilers, but has a more helpful error message if you accidentally use 128bit numbers without enabling the feature?

Or maybe we could work around it using some `build.rs` wizardry?

**Comment by KodrAus** [comment]
Hmm actually, if we wanted to do something with an explicit `i128` feature on `bincode` maybe it would be better if it looked like:

```rust
impl Serializer {
    #[cfg(feature = "i128")]
    fn serialize_i128(self, v: i128) -> Result<Self::Ok, Self::Error> {
        // use `byteorder` to serialize our value
    }

    serde_if_integer128! {
        #[cfg(not(feature = "i128"))]
        fn serialize_i128(self, v: i128) -> Result<Self::Ok, Self::Error> {
            let _ = v;
            Err(Error::custom("i128 is not supported. Enable the `i128` feature of `bincode`"))
        }

        ...
    }
}
```

So that enabling it always tried to implement the method, but if it's available and not implemented then we suggest the feature.

**Comment by TyOverby** [comment]
This looks like a good plan!  

Would you feel comfortable implementing it?  If not, I can get to it later this week.

**Comment by KodrAus** [comment]
@TyOverby Sure! I'm happy to submit a PR for this.

**Comment by KodrAus** [comment]
Hi @TyOverby! Are you happy to push out a `1.0.1` patch with the 128bit number support?

**Comment by TyOverby** [comment]
Published!
