### ISSUE TITLE
Crash on deserialize_from() with malformed data (attempting to allocate about 6.6 exabytes)

### ISSUE THREAD

**Issue by LeoTindall** [TyOverby/bincode#239]
Hi! The attached input (un-gzipped; github won't let me upload it raw) causes `deserialize_from()` to attempt to allocate 6.6 EB of memory.
[test.bincode.gz](https://github.com/TyOverby/bincode/files/2150593/test.bincode.gz)
![exabytes1](https://user-images.githubusercontent.com/3290365/42110292-2ebf6910-7ba6-11e8-8ceb-5d0440d32ac6.png)

**Comment by TyOverby** [comment]
Can you post the code that you are using to deserialize?

**Comment by LeoTindall** [comment]
I have a struct definition:

```rust
/// A gene variant from the ClinVar database.
#[derive(Debug, PartialEq, Deserialize)]
struct GeneVariant {
    gene: String,
    p_dot_name: Option<String>,
    c_dot_name: Option<String>,
}
```

This is deserialized in a loop:

```rust
loop {
        match bincode::deserialize_from(&mut rdr) {
            Ok(variant) => { 
                // Do things with the variant
            }
            Err(error) => match *error {
                bincode::ErrorKind::Io(ioerror) => match ioerror.kind() {
                    io::ErrorKind::UnexpectedEof => break,
                    _ => panic!("Error ingesting variants from bincode: {}", ioerror)
                }
                error => error!("Unable to parse variant: {}", error)
            }
        }
    }
```

**Comment by TyOverby** [comment]
try using the [limit](https://docs.rs/bincode/1.0.1/bincode/struct.Config.html#method.limit) method.

`bincode::config().limit(max number of bytes)`

**Comment by LeoTindall** [comment]
This fixes the issue, but I don't really understand why. Where is it getting that extra data from?

**Comment by TyOverby** [comment]
It's not getting extra data, it's preallocating a vector with *way* too much memory in expectation of a huge payload.

The first couple bytes that are decoded tell the String how long it's going to be, and it tries to pre-allocate all that memory for performance reasons.  This is why the `limit` api exists, to kill the entire process if too many bytes are asked to be read early in the process.

After reading through the code that does the pre-allocation, I think bincode can be much smarter smarter about preallocation in the non-limited areas.  I'll look into making this better.  In the meantime, I highly recommend using the `limit` api.

**Comment by LeoTindall** [comment]
Understood, thank you!

**Comment by TyOverby** [comment]
I've filed a new bug for the feature if you want to follow that one!
