### ISSUE TITLE
what is the behavior of deserialize_from

### ISSUE THREAD

**Issue by evnix** [TyOverby/bincode#249]
My struct looks as follows:

```
pub struct Record  {
    pub uuid:       [u8;16],
    pub error_count: i32,
    pub distance:    i64,
    pub data:       Vec<u8>
}
```
and then I write a loop to write around 1000 such Record appended to a file using serialize:
```
config().big_endian().serialize(&my_record)
```

Now when I do deserialize as follows, will it read the first record, if so, how will it know the exact size to read. (I could not find anything related to this in the docs)
```
    let record: Record = config().big_endian().deserialize_from(&file_read_handle)?;
```
if not, what is a good/right way to read such data (for example the 1000 records mentioned above.)

**Comment by TyOverby** [comment]
It won't know how many to read.  Your deserialization code will only read one.

**Comment by TyOverby** [comment]
If I were you, I'd put them in a vec and then serialize the vec.

Otherwise, you could just keep reading until you run out of bytes in the file?

**Comment by evnix** [comment]
> Otherwise, you could just keep reading until you run out of bytes in the file?
how will it know the exact size of a Record, as each record will be of variable size.

Let me put it another way, I am trying to understand if the below code is valid when Records are of variable size:

```
   while(has_more_data(file_read_handle)){
    let record: Record = config().big_endian().deserialize_from(&file_read_handle)?;
    //do something with the individual record
   }

```

**Comment by evnix** [comment]
an update,
The above code seems to work (I don't know how it works internally) but it saved me close to a 100 lines of code. :-)

**Comment by TyOverby** [comment]
Yes, it does know how to deserialize records of variable size.  The only way that the record is variable-length is when the the length of your `data` Vec changes.  Because bincode stores the length of vectors in the output, we can successfully accommodate changes in size.
