### ISSUE TITLE
Fetching old version of binorder

### ISSUE THREAD

**Issue by lambdaburrito** [TyOverby/bincode#25]
My Cargo.toml looks like this:

    [dependencies]
    bincode = "*"

However it cannot build because it is trying to fetch an old version of binorder: v.0.2.14

I've noticed in your Cargo.toml  it states it should be using v0.3.1 but it's ^v0.2.9 on the Cargo web site.

https://crates.io/crates/bincode

I've tried doing cargo update and that didn't help.

**Comment by TyOverby** [comment]
Oh, I forgot to publish to crates.io.  I'll do that now.

**Comment by TyOverby** [comment]
This should be fixed now!

**Comment by lambdaburrito** [comment]
Thanks for the quick resolution! :+1:
