### ISSUE TITLE
Expose a way to get the maximum encoded size for a give type

### ISSUE THREAD

**Issue by jrmuizel** [TyOverby/bincode#263]
This would be helpful speeding up serialization/deserialization because we can lift the length out completely and make it not dependent on the actual value.

**Comment by dtolnay** [comment]
Seems reasonable. I am closing the issue because I would prefer for this to live in a different crate -- it will need its own trait and derive macro to expose this information.

**Comment by jrmuizel** [comment]
I've started implementing this here: https://github.com/jrmuizel/bincode-size
