### ISSUE TITLE
can't find crate for `rustc_serialize`

### ISSUE THREAD

**Issue by lambdaburrito** [TyOverby/bincode#27]
I noticed you have fixed  bugs with the new nightly but looks like you haven't propogated the changes to Cargo.

.rs:8:1: 8:51 error: can't find crate for `rustc_serialize`
/home/jp/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.0.12/src/lib.rs:8 extern crate "rustc-serialize" as rustc_serialize;

**Comment by TyOverby** [comment]
I just published to crates.io.  Thanks for reminding me!
