### ISSUE TITLE
#![feature(unicode)]

### ISSUE THREAD

**Issue by spicavigo** [TyOverby/bincode#33]
With rustc (**1.0.0-beta.3 (5241bf9c3 2015-04-25) (built 2015-04-25)**)

I just created a dependency with `bincode = "*"` in my code. Now cargo build is saying

    /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.1.2/src/lib.rs:6:1: 6:21 error: unstable feature

    /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.1.2/src/lib.rs:6 #![feature(unicode)]
                                                                                         ^~~~~~~~~~~~~~~~~~~~
**note**: this feature may not be used in the beta release channel
**error**: aborting due to previous error
Could not compile `bincode`.

**Comment by TyOverby** [comment]
Fixed in efa1afd59c699cdcfdadba04c8cf5e77925c9f50

Run `cargo update -p bincode` to get the beta-compatible version.

This unfortunately adds an allocation to the middle of emitting chars, but hopefully that doesn't happen very often.

I'll change it back once the unicode crate stabilizes.
