### ISSUE TITLE
Add support for `RefBox<'a, [T]>` and `RefBox<'a, str>`

### ISSUE THREAD

**Issue by reem** [TyOverby/bincode#34]
These are useful for conservatively serializing `&str` and `&[T]` then deserializing to `Box<str>` and `Box<[T]>`, which are analogous to `String` and `Vec<u8>`.

**Comment by reem** [comment]
cc https://github.com/rust-lang/rustc-serialize/issues/103

**Comment by TyOverby** [comment]
I'm not familiar with boxed unsized types.  How does one go about making and using Box<str> and Box<[T]>?

**Comment by reem** [comment]
`Box<[T]>` is constructed via either `box static_array` or `Vec::into_boxed_slice`. It has the same representation as `&[T]` but is heap allocated and owned.

**Comment by reem** [comment]
You could also solve this issue with specific `RefVec<'a, T>` and `RefString<'a>` types, if the boxed-unsized-types is weird.

**Comment by TyOverby** [comment]
#37 Will close this issue once I add tests.
