### ISSUE TITLE
Decoding should return how much of the buffer was used

### ISSUE THREAD

**Issue by reem** [TyOverby/bincode#35]
This is so it is possible to parse from a large (e.g. ring) buffer and know when the current thing we are decoding has ended and another message has begun.

**Comment by TyOverby** [comment]
Good idea; I actually already collect that information, I'll just need to export it.

**Comment by TyOverby** [comment]
I'm reverting this because I don't think that the information is useful enough to put on the basic functions.  

You can still access this information by constructing the `DecoderReader`, decoding from that, then asking how many bytes were read.
