### ISSUE TITLE
struct deserialization should offer field-names to the passed visitor

### ISSUE THREAD

**Issue by oli-obk** [TyOverby/bincode#48]
Right now you treat structs like tuples, because they are laid out the same way in bincode's format. During serialization that works mostly fine (since serializers usually pass struct fields in the order in which they are declared). During deserialization you deserialize the struct through `visit_seq`. Structs are meant to be deserialized through `visit_map`.

See some context here: https://github.com/serde-rs/serde/issues/177

I think there could be room for improvement in serde wrt struct serialization to make sure that the serializer can choose the order of the elements it receives instead of the struct's `Deserialize` implementation.

cc @erickt

**Comment by TyOverby** [comment]
Would "offering" field names during deserialization require serializing them?

**Comment by oli-obk** [comment]
nope, You get a static array of the names. So basically it'd just be iterating through that array and using them as keys to pass to a `MapVisitor`.

**Comment by TyOverby** [comment]
I'll look into it today, thanks!

**Comment by TyOverby** [comment]
@erickt Could you take a look at this?  I tried playing with it, but I'm still really unsure about the serde interface.  Since you wrote the original implementation, do you think this would be a reasonable thing to add?

**Comment by dtolnay** [comment]
We no longer need this. Serde has embraced visit_seq as a way to deserialize braced structs.
