### ISSUE TITLE
bincode error while deserializing file with option

### ISSUE THREAD

**Issue by ghotiphud** [TyOverby/bincode#52]
```
bincode::serde::deserialize_from(&mut file, SizeLimit::Infinite).expect("bincode deserialize error");

thread '<main>' panicked at 'bincode deserialize error: InvalidEncoding(InvalidEncoding { desc: "invalid tag when decoding Option", detail: Some("Expected 0 or 1, got 11") })', ../src/libcore/result.rs:709
```

I'm going to attempt to build a repro case, but it might take me a while.  Thought maybe this would mean more to you than me.

**Comment by TyOverby** [comment]
Are you implementing the serde serializer and deserializer by hand, or are you using serde's compiler plugin to do it for you?

**Comment by ghotiphud** [comment]
I used serde_macros on nightly.

**Comment by TyOverby** [comment]
Hmm.  That shouldn't happen. 

Are you sure that the struct didn't change between when you serialized the file and when you deserialized it?

**Comment by ghotiphud** [comment]
I've just run it again with the same results. 

```
serialize_into(&mut file, &makes, SizeLimit::Infinite).unwrap();

deserialize_from(file, SizeLimit::Infinite)
```

**Comment by TyOverby** [comment]
Ok, I'll need to see your code, is it public somewhere?

**Comment by ghotiphud** [comment]
Gist for repro - https://gist.github.com/ghotiphud/c97ac187a088a45e7d0a

Library to gather data - https://github.com/ghotiphud/edmunds-rs

You'll need an API key to access the Edmunds Api, but I'll loan you my test one.  Should I send it to ty@pre-alpha.com?

**Comment by TyOverby** [comment]
I'm pretty sure that `#[serde(skip_serializing)]` will just flat-out break bincode.

Bincode relies on the serializer and deserializer following the **exact** same steps, so if serialization doesn't serialize something, and deserialization expects it to be there, then everything breaks.

I'll do some more experimenting and add this as a warning to the readme.

**Comment by ghotiphud** [comment]
That worked!  Is there any way to just ignore fields completely for serialization and deserialization?

**Comment by TyOverby** [comment]
It should be possible to define a newtype struct like this:

```rust

struct Ignore<T: Default>(T);

```

and then 
* have a custom serialize implementation that doesn't do anything.
* have a custom deserialize implementation that constructs a Default T.


This might be handy enough that I could just include it in Bincode.

**Comment by ghotiphud** [comment]
I think it would be most handy in serde, at least for my use case... basically saving a Json response off to a file while ignoring some fields.

**Comment by TyOverby** [comment]
Apparently serde has `#[serde(default)]` but it won't work with bincode (bincode has no idea if something is missing or not)
