### ISSUE TITLE
Deserialisation of PathBuf doesn't work

### ISSUE THREAD

**Issue by neon64** [TyOverby/bincode#53]
Deserialising a simple struct with a `PathBuf` inside fails with the error: `SyntaxError`

Can be reproduced by this Gist:
https://gist.github.com/neon64/03230cb40ff3bafed8ee#file-bincode_pathbuf-rs

    #![feature(plugin)]
    #![feature(custom_derive)]
    #![plugin(serde_macros)]

    extern crate serde;
    extern crate bincode;

    use std::path;
    use bincode::SizeLimit;
    use bincode::serde::{serialize, deserialize};

    #[derive(Serialize, Deserialize)]
    struct MyData {
        path: path::PathBuf
    }

    #[test]
    fn it_works() {
        let data = MyData {
            path: path::Path::new("foo").to_path_buf()
        };
        let ser = serialize(&data, SizeLimit::Infinite).unwrap();
        let de: MyData = deserialize(&ser).expect("bincode failed");
    }

It seems like it is just limited to bincode, as serde_json works for example.

**Comment by TyOverby** [comment]
The main issue is that Bincode was built for rustc-serialize, and there are some serde idioms that don't translate well.

The SyntaxError (updated to show useful information in c778cda42fc013c95e91b58ade2d235fe4475899) is hitting one of the things that bincode can't do.  Namely that Bincode does not support Deserializer::visit.

However, PathBuf probably shouldn't require the kind of hinting that Deserializer::visit uses.

Resolutions:

1. I'll open up a bug on Serde and see if I can get this fixed on their side.
2. For now, you can just encode / decode using Strings.  Sorry about the inconvenience.

**Comment by TyOverby** [comment]
This was fixed upstream in serde!
