### ISSUE TITLE
Get number of bytes written/read?

### ISSUE THREAD

**Issue by alexreg** [TyOverby/bincode#54]
Could the `serialize_into` and `deserialize_from` methods return the number of bytes written/read respectively? This would both handy and more efficient, since you already have to compute these values in these methods, and it thus saves an extra call to `serialized_size`.

**Comment by alexreg** [comment]
Hmm, on second though, I'm not sure how easy this is to add to code.

**Comment by TyOverby** [comment]
If you use the structs defined [here](http://tyoverby.com/bincode/bincode/rustc_serialize/index.html) to do the deserialization you can grab the number of bytes read.

By using the function encoded_size, you can get the size of the struct as it would be on the wire.

**Comment by alexreg** [comment]
It doesn't seem to be documented how to use those structs directly.

**Comment by TyOverby** [comment]
I've added documentation to [rustc-serizlize DecoderReader](http://tyoverby.com/bincode/bincode/rustc_serialize/struct.DecoderReader.html) and [serde Deserializer](http://tyoverby.com/bincode/bincode/serde/struct.Deserializer.html).  The `encoded_size` and `serialized_size` functions are already documented.

**Comment by alexreg** [comment]
Thanks for this. That’s quite handy.

Not sure if it bothers you, but there’s a typo in the docs – “bytes_red”. Otherwise good.

**Comment by TyOverby** [comment]
aah!  Thanks!
