### ISSUE TITLE
Allow struct members to be [de]serialised in a certain number of bits

### ISSUE THREAD

**Issue by aka-demik** [TyOverby/bincode#58]
It is often necessary for binary protocols.

A la:
```rust
#[derive(RustcEncodable, RustcDecodable, PartialEq)]
struct Entity {
    #[bits(4)]
    x: u8,
    #[bits(4)]
    y: u8,
}
```

**Comment by TyOverby** [comment]
This is practically impossible because bincode needs to work with rustc_serialize and serde; both of which are general enough that it would hard to get that information through them and back into the reader/writer in bincode.  

I suggest that you do something like this 

```rust
struct Entity {
    xy: u8,
}

impl Entity {
    fn x(&self) -> u8 {
        self.xy & 0xF
    }

    fn y(&self) -> u8 {
        self.xy & 0xF0
    }
}
```
