### ISSUE TITLE
Add new maintainers to the project

### ISSUE THREAD

**Issue by nox** [TyOverby/bincode#59]
Servo depends on bincode and it would be nice if releases were made more regularly.

**Comment by TyOverby** [comment]
I'd certainly be willing to accept some more maintainers.  

Having someone from Servo, and someone from Serde would be great.

**Comment by nox** [comment]
I am willing to be the one from Servo.

**Comment by TyOverby** [comment]
I've added you as a collaborator on github, as well as an owner on crates.io.

**Comment by nox** [comment]
Thanks a lot!

**Comment by TyOverby** [comment]
:tada:

**Comment by nox** [comment]
Cc @erickt as main Serde author.

**Comment by TyOverby** [comment]
Closing this for now.  Maybe some serde contributor would like to join later.

**Comment by erickt** [comment]
cc @dtolnay and @oli-obk.

Maybe we need a [crater](https://github.com/brson/taskcluster-crater)-ish tool for the serde ecosystem. We potentially now have 56 crates using us as a dependency :)
