### ISSUE TITLE
Deserialization in other languages

### ISSUE THREAD

**Issue by SuperFluffy** [TyOverby/bincode#62]
Will this library be suitable serialization in rust, and then deserialization in another language? The use case I have in mind is running expensive numerical simulations in rust, saving the result using e.g. bincode, and then performing some data analysis in python.

**Comment by TyOverby** [comment]
No, cooperating with other languages is a non-goal of Bincode.  Bincode is only for Rust->Rust communication and state serialization.  

For your use-case I would highly recommend [cap'n proto](https://capnproto.org/).
