### ISSUE TITLE
bincode deserialization with serde might be broken

### ISSUE THREAD

**Issue by iqualfragile** [TyOverby/bincode#74]
Example of some code that fails to run:
https://gist.github.com/iqualfragile/743cc39ac4199e0f669bae13b778474e

**Comment by TyOverby** [comment]
This is really unexpected.

Serde probably shouldn't be doing a dynamic visit for this code?

Here's an even smaller repro.

*input*
```
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]
extern crate bincode;

use bincode::SizeLimit;
use bincode::serde::{serialize, deserialize};

fn main() {
    let input = [0u8; 5];
    println!("{:?}", input);
    let serialized = serialize(&input, SizeLimit::Infinite).unwrap();
    println!("{:?}", serialized);
    let deserialized: [u8; 5]= deserialize(&serialized).unwrap();
    println!("{:?}", deserialized);
}
```

@erickt, do you know what's going on here?  Could you point me to the implementation of serialization and deserialization for arrays?

**Comment by TyOverby** [comment]
Edit: code appears to be here:
https://github.com/serde-rs/serde/blob/master/serde/src/de/impls.rs#L517

**Comment by TyOverby** [comment]
Oh, it's because we don't have `deserialize_fixed_size_array` implemented.

**Comment by iqualfragile** [comment]
Ok, is there something i can do to help fix this?

**Comment by TyOverby** [comment]
I'm a bit strapped for time right now, but if you wanted to look at implementing `deserialize_fixed_size_array` on the `Deserializer` struct, then everything should work.
