### ISSUE TITLE
fixed length arrays have their size encoded

### ISSUE THREAD

**Issue by oohal** [TyOverby/bincode#86]
When a encoding a structure that contains a fixed length array the length of the array is also encoded. For example, this code:

``` rust
extern crate rustc_serialize;
extern crate bincode;

use bincode::SizeLimit;
use bincode::rustc_serialize::encode;

#[derive(RustcEncodable)]
struct TestStruct {
    a : u16,
    b : [u8; 6],
}

fn main() {
    let test = TestStruct {a: 0xffff, b: [1, 2, 3, 4, 5, 6]};
    let encoded: Vec<u8> = encode(&test, SizeLimit::Infinite).unwrap();

    println!("header: {:?}", encoded);
}
```

Produces this output:

```
header: [255, 255, 0, 0, 0, 0, 0, 0, 0, 6, 1, 2, 3, 4, 5, 6]
```

This behaviour makes it hard to use bincode for unpacking externally defined binary formats (e.g ELF headers). I suppose this library isn't really designed for that, but it works well enough for BE formats so it would be nice to see this fixed in the next major version.

**Comment by TyOverby** [comment]
I don't think that there is a way to do this with rustc-serialize.  At least, there isn't a trait method for statically sized arrays.

**Comment by Matvey-Kuk** [comment]
+1 for this idea

**Comment by TyOverby** [comment]
This feature is only possible if we drop RustcSerialize support.  I'm planning on doing that eventually, but it's on the backlist until serde hits 1.0

**Comment by Matvey-Kuk** [comment]
@TyOverby thank you! Just wanted to mention there is somebody else who need this =)

**Comment by aldanor** [comment]
Very much in support of this as well. Now that serde 0.9 is out, is it a good time to revisit this?

**Comment by darfink** [comment]
I'd like to chime in on this as well. Working with external data and this issue hit me, ended up having to use a fork.

**Comment by mikedilger** [comment]
I also ran into this.  What if we change the code to skip these lengths if the `rustc_serialize` feature is disabled?

**Comment by TyOverby** [comment]
Since there's so much interest in this, I think I'll begin work on removing rustc-serialize support from bincode altogether.  I've wanted to do this for a long time, but since serde is hitting 1.0 and macros are landing, I think it'll be pretty reasonable to move on to.

**Comment by TyOverby** [comment]
rustc-serialize removal happening here: https://github.com/TyOverby/bincode/pull/95

**Comment by aldanor** [comment]
That's great, thanks! Given that this will be a (very-) breaking change release, does it make sense to break things a little further and add endianness support?
