### ISSUE TITLE
Add a Serializer that works with bytes crate's MutBuf instead of io::Write

### ISSUE THREAD

**Issue by tikue** [TyOverby/bincode#87]
See http://carllerche.github.io/bytes/bytes/trait.MutBuf.html

(And same with `Deserializer` / `Buf` / `io::Read`)

**Comment by TyOverby** [comment]
What implementors of MutBuf aren't also io::Write?

**Comment by tikue** [comment]
`bytes::BlockBuf` only impls `MutBuf` and `bytes::BlockBufCursor` only impls `Buf`, presumably because their memory isn't contiguous.

**Comment by tikue** [comment]
Actually I'm not sure why they don't impl `Read` and `Write`, cc @carllerche?

**Comment by tikue** [comment]
Ah, looks like you can bridge from MutBuf to Write, so closing this!
