### ISSUE TITLE
Support serde 0.9.X

### ISSUE THREAD

**Issue by dorny** [TyOverby/bincode#92]
Serde 0.9.0-rc1 is out (https://github.com/serde-rs/serde/issues/668) and there are some breaking changes.
It would be great to have a support for it. Thanks.

**Comment by dorny** [comment]
I have looked for breaking changes which causes troubles:
https://github.com/serde-rs/serde/commit/88debb3fb85f493c55373cbcc04c997ed0239c48 - Remove `SeqVisitor::end()` and `MapVisitor::end()`
https://github.com/serde-rs/serde/commit/738aa317339e2fa576b74345fab3a16e45da0cf8 - Enforce correct use of Deserialize trait
Most probably there will be more, these two are just result of my quick research (hoping it will be easy enough to be able to fix it by myself).

**Comment by dtolnay** [comment]
Here are the changes going into 0.9.0. You can see the ones marked with the "breaking change" label. https://github.com/serde-rs/serde/milestone/16?closed=1

In the next couple days as the release settles down, I will write up a thorough explanation of the changes and motivation for them as well as helpful notes for migrating. I would advise waiting for that before attempting to update. Then you will have about a week and a half to update in time for the Rust 1.15 release.

**Comment by dgriffen** [comment]
I've been working on this since I need it for a project I'm working on. I've got the rewrite almost complete apart from deserialize_enum. I'm not too familiar with serde or bincode but it seems that now for some reason the DeserializeSeed wants to call deserialize_struct_field.

**Comment by dtolnay** [comment]
This is a bug: https://github.com/serde-rs/serde/issues/722. I posted a workaround in that issue. [XDR](https://github.com/cavedweller/rust-xdr/blob/22e698deac2a799cb7dcdc8147f68ff06953a882/src/serde_xdr/deserializer.rs) has been using it successfully.

**Comment by dgriffen** [comment]
Wow, that was a fast response! I implemented the workaround and all the tests passed.
