### ISSUE TITLE
Polish all error messages

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#98]
The current error messages have an unfriendly Display representation. For example SerializeError in https://github.com/TyOverby/bincode/commit/9e47b71af6476c81ec3036c900399ac903b5fc40:

```rust
impl fmt::Display for SerializeError {
    fn fmt(&self, f: &mut fmt::Formatter) -> Result<(), fmt::Error> {
        match *self {
            SerializeError::IoError(ref err) => write!(f, "IoError: {}", err),
            SerializeError::Custom(ref s) => write!(f, "Custom Error {}", s),
            SerializeError::InfiniteSequence => write!(f, "InfiniteSequence"),
            SerializeError::SizeLimit => write!(f, "SizeLimit"),
        }
    }
}
```

Let's audit all the error messages in this crate and make sure everything has a self-explanatory message that a human can read and understand what went wrong.

**Comment by TyOverby** [comment]
I think a neat feature of the errors (once merged) would be tracking if they came from encoding or decoding. 

Example: 

`While decoding, bincode hit an IoError from the underlying reader: $IOERRORTEXT`
vs
`While encoding, bincode hit an IoError from the underlying writer: $IOERRORTEXT`

**Comment by dtolnay** [comment]
I filed individual issues for the error message problems I noticed.

**Comment by TyOverby** [comment]
Closed all of these (I think)
